name: Build and lint

on:
  pull_request:
    paths:
      ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "**/*.json", "**/*.md"]
  workflow_dispatch:
jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Build everything
        run: yarn run build
      - name: Lint everything
        run: yarn run lint
