name: RPC Test

on:
  pull_request:
    paths: ["packages/nitro-rpc-client", ".github/workflows/rpc-test.yml"]
  workflow_dispatch:
jobs:
  run-rpc-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.20.0"
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3

      # Install foundry so we can use it to run a chain instance
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # Get go-nitro
      - uses: actions/checkout@v3
        with:
          repository: "statechannels/go-nitro"
          path: "code/go-nitro"

      - name: Tidy
        run: go mod tidy
        working-directory: code/go-nitro

        # Start up a chain for the RPC server to work against
      - name: Run anvil chain
        run: anvil --host 0.0.0.0 --chain-id 1337 &

      - name: Run go-nitro RPC server
        run: go run . &> output.log &
        working-directory: code/go-nitro

      - name: Install dependencies
        run: yarn

      - name: Launch Address request using CLI tool and test against expectations
        run: bash ./test-against-server.sh
        working-directory: ./packages/nitro-rpc-client

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./**/*.log
