name: RPC Test

on:
  pull_request:
    paths: ["packages/nitro-rpc-client", ".github/workflows/rpc-test.yml"]
  workflow_dispatch:
jobs:
  run-rpc-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.20.0"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"

      # Install foundry so we can use it to run a chain instance
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # Get go-nitro
      - uses: actions/checkout@v3
        with:
          repository: "statechannels/go-nitro"
          path: "code/go-nitro"

      - name: Tidy
        run: go mod tidy
        working-directory: code/go-nitro

      - name: Run go-nitro RPC servers
        run: go run ./scripts/start-rpc-servers.go &> output.log &
        working-directory: code/go-nitro

      - name: Install dependencies
        run: yarn

      - name: Run Create Channels script
        # TODO: We could write a test specific script that creates channels and checks the results
        run: npx ts-node ./scripts/client-runner.ts create-channels &> output.log
        working-directory: ./packages/nitro-rpc-client

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./**/*.log
